#
# Macro file for "TestEm16.cc"
# (can be run in batch, without graphic)
#
#
#/control/verbose 2
#/run/verbose 2
#
/testem/target/setMat PS50_W45_CNT5
#/testem/target/setSize 1.8 mm
#
/run/initialize

/gun/particle gamma
/gun/energy 100 keV
#
# set up histos.  
#/analysis/setFileName PS25_W75_80keV_1pt8mm
#/analysis/h1/set 1 100 0   100 keV	#Edep Energy
#/analysis/h1/set 2 100 0   100 keV	#Flow Energy
#
#
#/run/beamOn 1000000
