#
# Macro file for "TestEm16.cc"
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
/testem/target/setMat PS25_W75
/testem/target/setSize 1.9 mm
#
/run/initialize

/gun/particle gamma
/gun/energy 80 keV
#
# set up histos.  
/analysis/setFileName PS25_W75_80keV_1pt9mm
/analysis/h1/set 1 100 0   100 keV	#Edep Energy
/analysis/h1/set 2 100 0   100 keV	#Flow Energy
#
#
/run/beamOn 1000000
